### ISSUE TITLE
Documentation is doubly wrong

### ISSUE THREAD

**Issue by LawrenceZ1A** [CuboidRaptor/Python-Beetroot#2]
README says that crash() broke, you fixed it, it broke again and then you fixed it. Or maybe it was broken from the start, you fixed it, it then broke, then you fixed it again and finally it broke once more. Is crash() broken right now or fixed?

**Comment by CuboidRaptor** [comment]
Whether or not `beetroot.crash()` works at the moment can depend on the python version, computer specs, and all sorts of other details, and like I mentioned in your other issue this module is very old and idfk if anything works anymore.

**Comment by LawrenceZ1A** [comment]
What would you recommend (Python version, computer, details) for beetroot.crash() to work as efficiently as possible? I need to know by April 1.
